"""Runtime configuration, resolved from environment variables.

All settings have safe defaults so the application boots and serves a working
demo with zero configuration. Supplying ``GROQ_API_KEY`` upgrades answers from
the built-in extractive engine to generative LLM answers (via Groq).
"""

from __future__ import annotations

import os
from dataclasses import dataclass


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return float(raw)
    except ValueError:
        return default


@dataclass(frozen=True)
class Settings:
    """Immutable application settings.

    The Groq API key is read from the environment only — it is never written to
    the repository. Set it locally in a (git-ignored) ``.env`` file or, in
    production, as a Vercel environment variable.
    """

    # LLM provider configuration. The demo runs fully without a key; if a key is
    # present, answers are generated by Groq with the extractive engine as a
    # fallback on any error.
    groq_api_key: str | None = os.getenv("GROQ_API_KEY") or None
    llm_model: str = os.getenv("LLM_MODEL", "llama-3.3-70b-versatile")
    llm_max_tokens: int = _env_int("LLM_MAX_TOKENS", 1024)
    llm_temperature: float = _env_float("LLM_TEMPERATURE", 0.1)

    # Retrieval configuration.
    default_top_k: int = _env_int("RETRIEVAL_TOP_K", 8)

    # Application metadata, surfaced by the API and UI.
    app_name: str = "Healthcare GraphRAG"
    app_tagline: str = "Patient Progress & Bottleneck Intelligence"

    @property
    def llm_enabled(self) -> bool:
        """Whether a hosted LLM is configured for generative answers."""
        return bool(self.groq_api_key)


settings = Settings()
