"""Answer generation: hosted Groq LLM with a deterministic extractive fallback.

When ``GROQ_API_KEY`` is configured, answers are generated by a Groq-hosted model
over the retrieved graph + document context. If no key is set, or the API call
fails, the engine falls back to a deterministic extractive answer assembled
directly from the graph evidence and bottleneck insights — so the demo always
returns a useful, grounded response.
"""

from __future__ import annotations

from .config import settings
from .dataset import Row

_SYSTEM_PROMPT = (
    "You are a healthcare GraphRAG assistant supporting care-team review. "
    "Use only the provided context. Do not diagnose and do not invent facts. "
    "Keep answers concise and evidence-based. This is decision-support only, "
    "not medical advice."
)

_ANSWER_TEMPLATE = (
    "Question:\n{question}\n\n"
    "Context:\n{context}\n\n"
    "Answer using exactly these sections:\n"
    "1. Direct Answer\n"
    "2. Key Evidence\n"
    "3. Bottlenecks / Risks\n"
    "4. Suggested Care-Team Review Actions"
)


def build_context(graph_facts: list[str], chunks: list[Row]) -> str:
    """Assemble the retrieval context string passed to the model."""
    parts: list[str] = []
    if graph_facts:
        parts.append("GRAPH FACTS:\n" + "\n".join(graph_facts))
    if chunks:
        lines = [
            f"[{c.get('chunk_id')}] patient={c.get('patient_id')} "
            f"date={c.get('note_date')} section={c.get('section_name')} "
            f"text={c.get('chunk_text')}"
            for c in chunks
        ]
        parts.append("DOCUMENT CHUNKS:\n" + "\n".join(lines))
    return "\n\n".join(parts)


def generate_answer(question: str, context: str) -> tuple[str | None, str | None]:
    """Generate an answer with a Groq-hosted model.

    Returns ``(answer, None)`` on success, ``(None, reason)`` if no key is
    configured or the call fails.
    """
    if not settings.llm_enabled:
        return None, "No LLM API key configured."

    try:
        from groq import Groq
    except ImportError:  # pragma: no cover - dependency is declared in requirements
        return None, "The 'groq' package is not installed."

    try:
        client = Groq(api_key=settings.groq_api_key)
        response = client.chat.completions.create(
            model=settings.llm_model,
            max_tokens=settings.llm_max_tokens,
            temperature=settings.llm_temperature,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": _ANSWER_TEMPLATE.format(question=question, context=context),
                },
            ],
        )
        text = (response.choices[0].message.content or "").strip()
        if not text:
            return None, "The model returned an empty response."
        return text, None
    except Exception as exc:  # noqa: BLE001 - surface any provider error to the fallback
        return None, f"{type(exc).__name__}: {exc}"


def extractive_answer(
    question: str,
    graph_facts: list[str],
    chunks: list[Row],
    insights: list[Row],
    patient_id: str,
    llm_error: str = "",
) -> str:
    """Assemble a deterministic, grounded answer directly from the evidence."""
    lines: list[str] = ["### Direct Answer"]
    lines.append(
        "This answer was assembled by the extractive GraphRAG engine "
        "(no language model was used)."
        + (f" Reason: {llm_error}" if llm_error else "")
    )

    if patient_id != "all":
        patient_insights = [
            r for r in insights if str(r.get("patient_id")) == str(patient_id)
        ]
        if patient_insights:
            lines.append("\n### Bottleneck Insights")
            for r in patient_insights:
                lines.append(f"- **{r.get('insight_type')}**: {r.get('bottleneck_summary')}")
                lines.append(f"  - Suggested review: {r.get('recommended_review_action')}")

    if graph_facts:
        lines.append("\n### Graph Evidence")
        lines.extend(f"- {fact}" for fact in graph_facts[:15])

    if chunks:
        lines.append("\n### Retrieved Evidence")
        for c in chunks[:10]:
            lines.append(
                f"- [{c.get('chunk_id')}] {c.get('note_date')} | "
                f"{c.get('section_name')}: {c.get('chunk_text')}"
            )

    return "\n".join(lines)
